CS2103JAN2018-F14-B2/main

docs/DeveloperGuide.adoc

**List of use cases added:**
- view full details of an appointment
- update pet owner's contact information
- retrieve medical history of a patient
- retrieve information of a particular owner
- generate pdf report on a particular pet patient
- generate pdf report on a particular pet owner
- add tags to a pet owner

Add use cases to Developer Guide

---

src/main/java/seedu/address/storage/AddressBookStorage.java
src/main/java/seedu/address/storage/StorageManager.java
src/main/java/seedu/address/storage/XmlAddressBookStorage.java

- Implemented backup API as required by LOs
- Note that handleAddressBookChangedEvent in StorageManager has not been modified. (In other words, API is implemented but never called / used)
- This is because in our actual product, we are dealing with local commits, and do not need / want to push commits to the cloud for privacy and security purposes.

Enhancement to Storage component

---

docs/UserGuide.adoc
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/ExitCommand.java
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/HelpCommand.java
src/main/java/seedu/address/logic/commands/HistoryCommand.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/commands/RedoCommand.java
src/main/java/seedu/address/logic/commands/SelectCommand.java
src/main/java/seedu/address/logic/commands/UndoCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/testutil/PersonUtil.java

- implement command aliases
- update JUnit test to include testing for command aliases
- update User Guide to include command aliases

Enhancement to Logic component

---

docs/UserGuide.adoc

- Create user accounts
- set user permissions
- support multi-users

add v2.0 features to User Guide

---

docs/DeveloperGuide.adoc

Modified Target user profile and Value proposition.
Removed 1 glossary term and added 1 glossary term.

Modified Target user profile and Value proposition

---

docs/DeveloperGuide.adoc

Updated glossary terms

---

docs/DeveloperGuide.adoc
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/model/AddressBookTest.java
src/test/java/seedu/address/model/ModelManagerTest.java

Remove Tag, edited some errors that was created.

Enhancement to Model Component

---

docs/AboutUs.adoc

- Removed irrelevant person
- changed back to johndoe to point back to valid file (will update portfolio later)

Updated AboutUs

---

src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml

Update UI to show NRIC field in Owner profile
Fixes #35

Update UI to show NRIC field in Owner profile

---

docs/DeveloperGuide.adoc
src/main/java/seedu/address/commons/events/model/AddressBookChangedEvent.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/ReadOnlyAddressBook.java
src/main/java/seedu/address/model/petpatient/UniquePetPatientList.java
src/main/java/seedu/address/storage/XmlAdaptedPetPatient.java
src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/model/AddressBookTest.java

- Note: tags for pet patients are not working
- Refer to Issue #44

Implemented storing of PetPatient details

---

src/main/java/seedu/address/model/petpatient/PetPatient.java

Added back constructor required for storage of PetPatients.

Fixed PetPatient class

---

src/main/resources/view/LightTheme.css

Update light theme

---

docs/DeveloperGuide.adoc

Update DG about calendar view

---

docs/DeveloperGuide.adoc

Update DG on certain prefaces

---

src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/storage/XmlAdaptedPetPatient.java
src/test/java/seedu/address/storage/XmlAdaptedPetPatientTest.java
src/test/java/seedu/address/testutil/PetPatientBuilder.java
src/test/java/seedu/address/testutil/TypicalPetPatients.java

- support storing of NRIC
- fixed type in AddressBook
- added storage tests
Refer to Issue #67.
Fixes #53.
Note: Tags still in progress

Storage Enhancements for PetPatients

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/systemtests/EditCommandSystemTest.java

- Implemented parsing
- Implemented basic logic for EditCommand
- Dependencies not resolved yet (checking logic has yet to be implemented)
- Editing of PetPatients and Appointments not supported yet
- Updated JUnit tests
Fixes #106.
Fixes #107.
Fixes #108.

Implemented EditCommand

---

docs/DeveloperGuide.adoc

Revised priorities of user stories

---

src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/UndoableCommandTest.java

Updated delete command to show relevant appointments and pet patients being deleted as well upon force delete.
fixes #114

Update delete command

---

src/test/java/seedu/address/logic/commands/AddCommandTest.java

Update and add new JUnit tests for AddCommand

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java

- Slight code improvement for AddCommand.java (2 methods moved to model component)
- Updated equals() method for AddCommand.java
- Updated AddCommandParser
- Add JUnit tests for AddCommand and AddCommandParser
- Reorganized CommandTestUtil.java and added more test variables
Fixes #110 
Fixes #124

Update code and add JUnit tests for Add command

---

src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/testutil/PetPatientUtil.java
src/test/java/seedu/address/testutil/TypicalAddressBook.java
src/test/java/seedu/address/testutil/TypicalAppointments.java
src/test/java/seedu/address/testutil/TypicalPersons.java
src/test/java/seedu/address/testutil/TypicalPetPatients.java
src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
src/test/java/systemtests/AddCommandSystemTest.java
src/test/java/systemtests/AddressBookSystemTest.java

#125 
- Created new class TypicalAddressBook: getTypicalAddressBook() method will add Persons, PetPatients and Appointments
- Created utility class for PetPatient (for JUnit tests in AddCommandSystemTest)
- Added JUnit tests for AddCommandIntegrationTest and AddCommandSystemTest
- Updated/added various test values

Add JUnit tests 

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/model/person/Nric.java
src/main/java/seedu/address/storage/XmlAdaptedAppointment.java
src/main/java/seedu/address/ui/CalendarWindow.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/java/seedu/address/ui/PetPatientCard.java
src/main/java/seedu/address/ui/PetPatientListPanel.java
src/main/resources/view/CalendarPanel.fxml
src/main/resources/view/DarkTheme.css
src/main/resources/view/MainWindow.fxml
src/main/resources/view/PetPatientListCard.fxml
src/main/resources/view/PetPatientListPanel.fxml
src/test/java/guitests/guihandles/CalendarPanelHandle.java
src/test/java/guitests/guihandles/MainWindowHandle.java
src/test/java/guitests/guihandles/PetPatientCardHandle.java
src/test/java/guitests/guihandles/PetPatientListPanelHandle.java
src/test/java/seedu/address/ui/PetPatientCardTest.java
src/test/java/seedu/address/ui/PetPatientListPanelTest.java
src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
src/test/java/systemtests/AddCommandSystemTest.java
src/test/java/systemtests/AddressBookSystemTest.java
src/test/java/systemtests/EditCommandSystemTest.java

Show appointment & Collate

---

src/main/java/seedu/address/ui/CommandBox.java

Update autocomplete case-insensitive

---

docs/UserGuide.adoc

Logo fix for warning and important boxes

---

src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/test/java/seedu/address/testutil/PetPatientUtil.java
src/test/java/seedu/address/testutil/TypicalPetPatients.java
src/test/java/systemtests/AddCommandSystemTest.java

Update collate and update addCommandSystemTest

---

build.gradle
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/appointment/exceptions/AppointmentDependencyNotEmptyException.java
src/main/java/seedu/address/model/appointment/exceptions/AppointmentNotFoundException.java
src/main/java/seedu/address/model/petpatient/exceptions/PetDependencyNotEmptyException.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/commands/FindCommandTest.java
src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
src/test/java/seedu/address/testutil/TypicalPersons.java
src/test/java/seedu/address/testutil/TypicalPetPatients.java
src/test/java/seedu/address/ui/CommandBoxTest.java
src/test/java/systemtests/DeleteCommandSystemTest.java
src/test/java/systemtests/FindCommandSystemTest.java

- Fixed a random system.out line in delete command
- Fixed #165 
- Fixed a comment for appointment not found exception, added some message for dependency not empty exceptions
- Changed the build jar file from addressbook to medeina.
- Added a new dog pet patient with tag, fixed command box test error that appeared with new pet, removed an unused method from typicalpersons.
- Closes #167 
- Does part of #168

Fixes to some bugs, Added test cases for Delete and Find

---

src/main/java/seedu/address/commons/core/GuiSettings.java
src/main/java/seedu/address/logic/commands/ChangeThemeCommand.java
src/main/java/seedu/address/logic/parser/ChangeThemeCommandParser.java
src/main/java/seedu/address/model/UserPrefs.java
src/main/java/seedu/address/model/theme/Theme.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/resources/view/MainWindow.fxml
src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
src/test/java/seedu/address/TestApp.java
src/test/java/seedu/address/logic/commands/ChangeThemeCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/model/theme/ThemeTest.java
src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
src/test/java/seedu/address/storage/StorageManagerTest.java
src/test/java/seedu/address/testutil/TypicalThemes.java

- fixes #169 
- fixes #171 
@chialejing @Robert-Peng @wynonaK 
Please **delete preferences.json and data/addressbook.xml**, start the application and add something to Medeina so that data/medeina.xml will be created in your local folder.

Update UserPrefs and store theme selection in preferences.json

---

src/main/java/seedu/address/ui/CalendarWindow.java

Appointments now display NRIC and text only

Appointments now display NRIC and text only

---

src/main/java/seedu/address/model/appointment/Appointment.java
src/main/java/seedu/address/ui/CalendarWindow.java

Appointment now can show everything including NRIC, name, remark and types.

View appointment

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/ui/Autocomplete.java
src/test/java/guitests/guihandles/CommandBoxHandle.java
src/test/java/seedu/address/ui/CommandBoxTest.java

fixes #198 
Added JUnit tests for autocomplete

Improve autocomplete for tags

---

src/main/java/seedu/address/commons/util/StringUtil.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/ui/Autocomplete.java
src/main/java/seedu/address/ui/CommandBox.java
src/test/java/seedu/address/ui/CommandBoxTest.java

fixes #204 
closes #93 
closes #48 
- Updated and added new JUnit tests for autocomplete
- Also removed autocomplete suggestions for pet patient names for "find" command.
For consistency with no autocomplete suggestion for person name.
- Renamed some variables
- Help @wynonaK to update her collate for SampleDataUtil

Implement descriptions for options and prefixes in autocomplete drop down menu

---

src/main/resources/view/CalendarPanel.fxml
src/main/resources/view/DarkTheme.css
src/main/resources/view/LightTheme.css

Fix List view color bug

---

docs/UserGuide.adoc

- Update UG structure to include a new CLI section that will comprise command format and autocomplete.
- Renamed 'Features' section to 'Medeina's Commands'
- Moved all future enhancements to a new section of its own
- Move data saving into a new section of its own
- Removed redundant summary listing of commands
- Add a new table in 'Command Summary 'for Personalisation Command e.g. theme command

Modify UG structure and made some amendments

---

src/main/resources/view/DarkTheme.css
src/main/resources/view/LightTheme.css
src/main/resources/view/PersonListPanel.fxml
src/main/resources/view/PetPatientListPanel.fxml

Show tabs for each panelList
#63

Show tabs for each panelList

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/testutil/TypicalIndexes.java

- EditCommandParserTest completed

Edit Command Tests

---

collated/functional/Robert-Peng.md
collated/functional/aquarinte-reused.md
collated/functional/aquarinte.md
collated/functional/chialejing-reused.md
collated/functional/chialejing.md
collated/functional/wynonaK.md
collated/test/Robert-Peng.md
collated/test/aquarinte.md
collated/test/chialejing.md
collated/test/wynonaK.md
src/main/resources/view/LightTheme.css

- Remove collate author (myself) from LightTheme.css
- Update collate files for v1.5rc

Update collate files

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java

More Exception update to fix return messages.

More Exception update

---

src/main/java/seedu/address/logic/commands/EditCommand.java

- updated messages for consistency

Updated Error Messages

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java

- should call from whole appointment list instead of filtered list

Update Error for Edit Command

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/ui/Autocomplete.java
src/main/java/seedu/address/ui/CommandBox.java

Some code refactoring and made autocomplete work only for valid commands
Updated messages

Minor code update

---

docs/UserGuide.adoc

- replaced "person" with "contact"
- updated FAQ with disclaimer (if edit data file directly, not considered a bug if cannot open, you shouldn't be doing that in the first place, please ._.)
- better structure for FAQ
- user friendly language + more details for FAQ
- minor edits to edit and command summary section

Updated UG

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/test/java/systemtests/EditCommandSystemTest.java

- if check for same appointment timing, then we cannot check whether remarks are being edited
- no choice but to disable check for same appointment timing

Fix + Added JUnit Test for EditCommand
